#!/bin/bash
# =============================================================================
# Generate Component Certificates
# =============================================================================
# This script generates TLS certificates for all Kubernetes components using
# the CA generated by generate-ca.sh.
#
# Components:
#   - kube-apiserver (CN=kube-apiserver, server cert with SANs)
#   - etcd (CN=etcd, server cert with SANs)
#   - kubelet (CN=system:node:<worker-name>, O=system:nodes)
#   - kube-proxy (CN=system:kube-proxy, O=system:node-proxier)
#   - kube-controller-manager (CN=system:kube-controller-manager)
#   - kube-scheduler (CN=system:kube-scheduler)
#   - service-account (CN=service-accounts, for signing SA tokens)
#   - admin (CN=admin, O=system:masters)
#
# Prerequisites:
#   - CA certificate and key generated (run generate-ca.sh first)
#   - cfssl and cfssljson installed
#   - variables.env configured with CONTROL_PLANE_IP and WORKER_NODE_IP
#
# Output:
#   - configs/pki/<component>.pem       (certificate)
#   - configs/pki/<component>-key.pem   (private key)
# =============================================================================

set -euo pipefail

# Source centralized variables
source "$(dirname "$0")/../../variables.env"

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
PKI_DIR="${PROJECT_ROOT}/configs/pki"

# -----------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------
log_info() {
    echo "[INFO] $1"
}

log_error() {
    echo "[ERROR] $1" >&2
}

log_success() {
    echo "[SUCCESS] $1"
}

check_prerequisites() {
    log_info "Checking prerequisites..."

    if ! command -v cfssl &>/dev/null; then
        log_error "cfssl is not installed."
        exit 1
    fi

    if ! command -v cfssljson &>/dev/null; then
        log_error "cfssljson is not installed."
        exit 1
    fi

    if [[ ! -f "${PKI_DIR}/ca.pem" ]] || [[ ! -f "${PKI_DIR}/ca-key.pem" ]]; then
        log_error "CA certificate or key not found. Run generate-ca.sh first."
        exit 1
    fi

    if [[ ! -f "${PKI_DIR}/ca-config.json" ]]; then
        log_error "CA config not found. Run generate-ca.sh first."
        exit 1
    fi

    if [[ -z "${CONTROL_PLANE_IP}" ]]; then
        log_error "CONTROL_PLANE_IP is not set in variables.env."
        log_error "Set it to the control plane node's IP address after provisioning."
        exit 1
    fi

    if [[ -z "${WORKER_NODE_IP}" ]]; then
        log_error "WORKER_NODE_IP is not set in variables.env."
        log_error "Set it to the worker node's IP address after provisioning."
        exit 1
    fi

    log_info "All prerequisites met."
}

generate_cert() {
    local name="$1"
    local csr_file="$2"

    log_info "Generating certificate: ${name}..."

    cd "${PKI_DIR}"
    cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes \
        "${csr_file}" | cfssljson -bare "${name}"

    # Clean up CSR file
    rm -f "${PKI_DIR}/${name}.csr"

    log_success "  Certificate: ${PKI_DIR}/${name}.pem"
    log_success "  Private Key: ${PKI_DIR}/${name}-key.pem"
}

# -----------------------------------------------------------------------------
# Certificate Generation Functions
# -----------------------------------------------------------------------------

generate_admin_cert() {
    log_info "--- Admin Certificate ---"
    log_info "  CN=admin, O=system:masters"

    cat > "${PKI_DIR}/admin-csr.json" <<EOF
{
  "CN": "admin",
  "key": {
    "algo": "rsa",
    "size": ${CA_KEY_SIZE}
  },
  "names": [
    {
      "C": "BR",
      "L": "Sao Paulo",
      "O": "system:masters",
      "OU": "k8s-lab",
      "ST": "Sao Paulo"
    }
  ]
}
EOF

    generate_cert "admin" "${PKI_DIR}/admin-csr.json"
}

generate_kube_apiserver_cert() {
    log_info "--- kube-apiserver Certificate ---"
    log_info "  CN=kube-apiserver"
    log_info "  SANs: kubernetes, kubernetes.default, kubernetes.default.svc,"
    log_info "        kubernetes.default.svc.cluster.local, 10.96.0.1,"
    log_info "        ${CONTROL_PLANE_IP}, 127.0.0.1"

    cat > "${PKI_DIR}/kube-apiserver-csr.json" <<EOF
{
  "CN": "kube-apiserver",
  "key": {
    "algo": "rsa",
    "size": ${CA_KEY_SIZE}
  },
  "hosts": [
    "kubernetes",
    "kubernetes.default",
    "kubernetes.default.svc",
    "kubernetes.default.svc.cluster.local",
    "10.96.0.1",
    "${CONTROL_PLANE_IP}",
    "127.0.0.1"
  ],
  "names": [
    {
      "C": "BR",
      "L": "Sao Paulo",
      "O": "Kubernetes",
      "OU": "k8s-lab",
      "ST": "Sao Paulo"
    }
  ]
}
EOF

    generate_cert "kube-apiserver" "${PKI_DIR}/kube-apiserver-csr.json"
}

generate_etcd_cert() {
    log_info "--- etcd Certificate ---"
    log_info "  CN=etcd"
    log_info "  SANs: ${CONTROL_PLANE_IP}, 127.0.0.1, localhost"

    cat > "${PKI_DIR}/etcd-csr.json" <<EOF
{
  "CN": "etcd",
  "key": {
    "algo": "rsa",
    "size": ${CA_KEY_SIZE}
  },
  "hosts": [
    "${CONTROL_PLANE_IP}",
    "127.0.0.1",
    "localhost"
  ],
  "names": [
    {
      "C": "BR",
      "L": "Sao Paulo",
      "O": "Kubernetes",
      "OU": "k8s-lab",
      "ST": "Sao Paulo"
    }
  ]
}
EOF

    generate_cert "etcd" "${PKI_DIR}/etcd-csr.json"
}

generate_kubelet_cert() {
    log_info "--- kubelet Certificate ---"
    log_info "  CN=system:node:${WORKER_NODE_NAME}, O=system:nodes"

    cat > "${PKI_DIR}/kubelet-csr.json" <<EOF
{
  "CN": "system:node:${WORKER_NODE_NAME}",
  "key": {
    "algo": "rsa",
    "size": ${CA_KEY_SIZE}
  },
  "hosts": [
    "${WORKER_NODE_IP}",
    "${WORKER_NODE_NAME}"
  ],
  "names": [
    {
      "C": "BR",
      "L": "Sao Paulo",
      "O": "system:nodes",
      "OU": "k8s-lab",
      "ST": "Sao Paulo"
    }
  ]
}
EOF

    generate_cert "kubelet" "${PKI_DIR}/kubelet-csr.json"
}

generate_kube_proxy_cert() {
    log_info "--- kube-proxy Certificate ---"
    log_info "  CN=system:kube-proxy, O=system:node-proxier"

    cat > "${PKI_DIR}/kube-proxy-csr.json" <<EOF
{
  "CN": "system:kube-proxy",
  "key": {
    "algo": "rsa",
    "size": ${CA_KEY_SIZE}
  },
  "names": [
    {
      "C": "BR",
      "L": "Sao Paulo",
      "O": "system:node-proxier",
      "OU": "k8s-lab",
      "ST": "Sao Paulo"
    }
  ]
}
EOF

    generate_cert "kube-proxy" "${PKI_DIR}/kube-proxy-csr.json"
}

generate_kube_controller_manager_cert() {
    log_info "--- kube-controller-manager Certificate ---"
    log_info "  CN=system:kube-controller-manager"

    cat > "${PKI_DIR}/kube-controller-manager-csr.json" <<EOF
{
  "CN": "system:kube-controller-manager",
  "key": {
    "algo": "rsa",
    "size": ${CA_KEY_SIZE}
  },
  "names": [
    {
      "C": "BR",
      "L": "Sao Paulo",
      "O": "system:kube-controller-manager",
      "OU": "k8s-lab",
      "ST": "Sao Paulo"
    }
  ]
}
EOF

    generate_cert "kube-controller-manager" "${PKI_DIR}/kube-controller-manager-csr.json"
}

generate_kube_scheduler_cert() {
    log_info "--- kube-scheduler Certificate ---"
    log_info "  CN=system:kube-scheduler"

    cat > "${PKI_DIR}/kube-scheduler-csr.json" <<EOF
{
  "CN": "system:kube-scheduler",
  "key": {
    "algo": "rsa",
    "size": ${CA_KEY_SIZE}
  },
  "names": [
    {
      "C": "BR",
      "L": "Sao Paulo",
      "O": "system:kube-scheduler",
      "OU": "k8s-lab",
      "ST": "Sao Paulo"
    }
  ]
}
EOF

    generate_cert "kube-scheduler" "${PKI_DIR}/kube-scheduler-csr.json"
}

generate_service_account_cert() {
    log_info "--- Service Account Certificate ---"
    log_info "  CN=service-accounts (used for signing SA tokens)"

    cat > "${PKI_DIR}/service-account-csr.json" <<EOF
{
  "CN": "service-accounts",
  "key": {
    "algo": "rsa",
    "size": ${CA_KEY_SIZE}
  },
  "names": [
    {
      "C": "BR",
      "L": "Sao Paulo",
      "O": "Kubernetes",
      "OU": "k8s-lab",
      "ST": "Sao Paulo"
    }
  ]
}
EOF

    generate_cert "service-account" "${PKI_DIR}/service-account-csr.json"
}

# -----------------------------------------------------------------------------
# Main Execution
# -----------------------------------------------------------------------------
main() {
    log_info "=========================================="
    log_info "Generating Kubernetes Component Certificates"
    log_info "=========================================="
    log_info ""
    log_info "Control Plane IP: ${CONTROL_PLANE_IP}"
    log_info "Worker Node IP:   ${WORKER_NODE_IP}"
    log_info "Worker Node Name: ${WORKER_NODE_NAME}"
    log_info ""

    check_prerequisites

    # Generate all component certificates
    generate_admin_cert
    echo ""
    generate_kube_apiserver_cert
    echo ""
    generate_etcd_cert
    echo ""
    generate_kubelet_cert
    echo ""
    generate_kube_proxy_cert
    echo ""
    generate_kube_controller_manager_cert
    echo ""
    generate_kube_scheduler_cert
    echo ""
    generate_service_account_cert

    log_info ""
    log_info "=========================================="
    log_success "All component certificates generated!"
    log_info "=========================================="
    log_info ""
    log_info "Generated certificates:"
    log_info "  - admin.pem / admin-key.pem"
    log_info "  - kube-apiserver.pem / kube-apiserver-key.pem"
    log_info "  - etcd.pem / etcd-key.pem"
    log_info "  - kubelet.pem / kubelet-key.pem"
    log_info "  - kube-proxy.pem / kube-proxy-key.pem"
    log_info "  - kube-controller-manager.pem / kube-controller-manager-key.pem"
    log_info "  - kube-scheduler.pem / kube-scheduler-key.pem"
    log_info "  - service-account.pem / service-account-key.pem"
    log_info ""
    log_info "Next step: Run distribute-certs.sh to copy certificates to cluster nodes."
}

main "$@"
